### PR TITLE
Make the 'build-all' target clean up after itself

### PR DESCRIPTION
**Pull request by cdisselkoen**
Perhaps a little unsophisticated, but solves my problem in #4.  We assume the user isn't keeping anything important in Arduino-Boards/libraries/current-libraries.

### CODE REVIEW

**Comment by obra** [comment]
Thanks!

do we actually need the -rf for a symlink? (removing it just protects a bit against accidentally killing real content)

**Comment by algernon** [comment]
We need either the `rm -rf`, or we need to remove the symlink(s) inside. I think `rm -rf` is fine in this case, because the directory is temporary, and will be removed anyway.

As another option, we could use `mktemp`, and create a really temporary directory. If we fail to remove that, another build will still succeed - we'll just leave some junk in `/tmp`.

**Comment by obra** [comment]
The actual path to that directory matters. Arduino is doing alphabetical
order for dependency resolution. (?!?!?!?!)

But gotcha. I misread what was going on.

**Comment by algernon** [comment]
No, it doesn't use alphabetical order, that was a false assumption I made, so we can put the temporary directory wherever.

**Comment by obra** [comment]
oh! ok then. i feel better

**Comment by obra** [comment]
Using an actual temp dir seems like a win.

**Comment by algernon** [comment]
I'd merge this, and migrate to a proper temp dir later (no idea when I'll get around to it).

**Pull request merged**
